minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
allowBuilds:
  esbuild: true
